### ISSUE TITLE
Use Python APIs to get response corresponding to arki-query --json --summary-short --annotate

### ISSUE THREAD

**Issue by bchiavarini** [ARPA-SIMC/arkimet#230] opened 2020-06-26 10:42 UTC
Hi, i'm trying to use Python APIs in order to get a response corresponding to the one given by` arki-query --json --summary-short --annotate` command.

Here's the code i'm using:
``` python
import io
import json
import arkimet as arki
cfg = arki.cfg.Sections.parse('/arkimet/config/arkimet.conf')
dt = cfg.section('vlm5')
source = arki.dataset.Reader(dt)
summary = source.query_summary('level:GRIB1,1;product:GRIB1,80,2,1')
with io.BytesIO() as out:
	summary.write_short(out,format="json")
	out.seek(0)
	summary_dict = json.load(out)
```
_**Note**: I am using this workaround to get a python dictionary of summary items as  `summary.to_python()` is raising to me a `Segmentation fault (core dumped)` error_

The first issue is that, as this code works with `summary.write(out,format="json")`, using `write_short()` method raises the following error:
```
SystemError: <built-in method write_short of arkimet.Summary object at 0x7fc23585f3b0> returned NULL without setting an error
```

The second question is: how can i add descriptions for each metadata in this resulting summary with Python APIs as i get using the `--annotation` flag in command line?

Thanks for your help!

**Comment by edigiacomo** [comment] 2020-07-02 12:10
Ciao Beatrice, sorry for the late reply.

> summary.to_python() is raising to me a Segmentation fault (core dumped) error

What arkimet version are you using? I've tried with `arkimet-1.27-1` and `summary.to_python()` works fine.

> The second question is: how can i add descriptions for each metadata in this resulting summary with Python APIs as i get using the `--annotation` flag in command line?

I forward this question to @spanezz

**Comment by spanezz** [comment] 2020-07-06 08:47
I reproduced and fixed (not pushed yet) the `write_short` issue.

Could you write the summary that causes `to_python()` to segfault to a file somehow and send it? I'd like to try to debug that segfault, too.

I'll now look at how formatters are or can be made accessible from python

**Comment by bchiavarini** [comment] 2020-07-06 11:00
thanks!
We are using Arkimet 1.27 version too. I attach a zip containing the bufr sample we had imported in our local dballe to testing the code written in the previous post and the txt of the summary i got in the `summary_dict` variable from that code.
Here's the code is raising the segmentation fault (i tested it directly form a python console and not launching a python script):
``` python
import arkimet as arki
cfg = arki.cfg.Sections.parse('/arkimet/config/arkimet.conf')
dt = cfg.section('vlm5')
source = arki.dataset.Reader(dt)
summary = source.query_summary('level:GRIB1,1;product:GRIB1,80,2,1')
[sample and summary.zip](https://github.com/ARPA-SIMC/arkimet/files/4878438/sample.and.summary.zip)
sum = summary.to_python()
Segmentation fault (core dumped)
```

**Comment by spanezz** [comment] 2020-07-06 13:29
Is the `sample.bufr` in the zipfile the file you got from the arkimet dataset? Something seems strange to me because in `source.query_summary('level:GRIB1,1;product:GRIB1,80,2,1')` the expression matches GRIB products instead of BUFR products

**Comment by bchiavarini** [comment] 2020-07-06 13:49
that's right, sorry. In these days i'm working mainly with bufr files and i got confused. 
The actual sample is a grib file in an arkimet archive that i can't attach here because the filesize is too big but you can find [here](https://github.com/mdantonio-c/mistral-hub/blob/datasets/data/arkimet/arkimet.zip)

**Comment by spanezz** [comment] 2020-07-06 14:33
Thanks! I tried <https://github.com/mdantonio-c/mistral-hub/blob/datasets/data/arkimet/arkimet.zip> and I couldn't find a `vlm5` dataset in it. I tried the `lm5` dataset that it contains, but a summary with query `level:GRIB1,1;product:GRIB1,80,2,1` produces no results

**Comment by bchiavarini** [comment] 2020-07-06 16:56
it's true, sorry again, i have noticed that locally i am using an other arkimet dataset which is too big to be updated in github..

**Comment by spanezz** [comment] 2020-07-06 17:08
Is it possible to post only the output of `arki-query 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5` ?

**Comment by bchiavarini** [comment] 2020-07-06 17:25
Sure!
`arki-query --json 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5`

```
{"i":[{"t":"source","s":"BLOB","f":"grib","b":"","file":"\/arkimet\/datasets\/vlm5\/2019\/06-21.grib","ofs":656454624,"sz":1210914},{"t":"origin","s":"GRIB1","ce":80,"sc":255,"pr":22},{"t":"product","s":"GRIB1","or":80,"ta":2,"pr":1},{"t":"level","s":"GRIB1","lt":1},{"t":"timerange","s":"GRIB1","ty":0,"un":1,"p1":1,"p2":0},{"t":"reftime","s":"POSITION","ti":[2019,6,21,0,0,0]},{"t":"area","s":"GRIB","va":{"Ni":1083,"Nj":559,"latfirst":-13050000,"latlast":12060000,"latp":-47000000,"lonfirst":-25290000,"lonlast":23400000,"lonp":10000000,"rot":0,"type":10}},{"t":"proddef","s":"GRIB","va":{"tod":1}},{"t":"run","s":"MINUTE","va":0}],"n":[{"t":"note","ti":[2019,6,24,8,53,0],"va":"Scanned from lfff00010000:656454624+1210914"}]}
{"i":[{"t":"source","s":"BLOB","f":"grib","b":"","file":"\/arkimet\/datasets\/vlm5\/2019\/06-24.grib","ofs":540218400,"sz":1210914},{"t":"origin","s":"GRIB1","ce":80,"sc":255,"pr":22},{"t":"product","s":"GRIB1","or":80,"ta":2,"pr":1},{"t":"level","s":"GRIB1","lt":1},{"t":"timerange","s":"GRIB1","ty":0,"un":1,"p1":0,"p2":0},{"t":"reftime","s":"POSITION","ti":[2019,6,24,0,0,0]},{"t":"area","s":"GRIB","va":{"Ni":1083,"Nj":559,"latfirst":-13050000,"latlast":12060000,"latp":-47000000,"lonfirst":-25290000,"lonlast":23400000,"lonp":10000000,"rot":0,"type":10}},{"t":"proddef","s":"GRIB","va":{"tod":1}},{"t":"run","s":"MINUTE","va":0}],"n":[{"t":"note","ti":[2019,6,24,8,51,36],"va":"Scanned from lfff00000000:540218400+1210914"}]}
```
while the simple `arki-query 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5` has a less legible output:
```
MD�P�P��        _NiA;NjAlatfirstJ� �latlastB�`latpK�)lonfirstK��lonlastCe@lonpB���rottype

tod1���@+Scanned from lfff00010000:656454624+12109145grib&/arkimet/datasets/vlm5/2019/06-21.grib�点��IMD�P�P��  _NiA;NjAlatfirstJ� �latlastB�`latpK�)lonfirstK��lonlastCe@lonpB���rottype

tod1����+Scanned from lfff00000000:540218400+12109145grib&/arkimet/datasets/vlm5/2019/06-24.grib��́��I
```

**Comment by spanezz** [comment] 2020-07-06 21:05
Yes, the output of just `arki-query 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5` is binary data. It can be redirected to a file with `arki-query 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5 > file.arkimet` or `arki-query 'level:GRIB1,1;product:GRIB1,80,2,1' vlm5 -o file.arkimet`, and then you can attach the output file as usual

**Comment by bchiavarini** [comment] 2020-07-07 07:25
ok, thanks! 
here's the output 
[arki_query_output.zip](https://github.com/ARPA-SIMC/arkimet/files/4883196/arki_query_output.zip)

**Comment by spanezz** [comment] 2020-07-07 08:30
Thanks! I still can't reproduce the segfault. Can you try this code and tell me if it segfaults for you?
```py
        ds = arkimet.dataset.Reader({
            "format": "arkimet",
            "name": "issue230",
            "path": "arki_query_output.arkimet",
            "type": "file",
        })
        summary = ds.query_summary()
        summary.to_python()
```

**Comment by bchiavarini** [comment] 2020-07-07 08:48
yes, also with this code i'm getting a segmentation fault. I am working with a python terminal inside a docker container, i don't know if this can affect this issue..

**Comment by edigiacomo** [comment] 2020-07-07 09:09
Unfortunately, I cannot reproduce the segfault in the docker container.

```
$ head -n1 /etc/*-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"

$ cat <<EOF > /tmp/test.py
import arkimet
ds = arkimet.dataset.Reader({
            "format": "arkimet",
            "name": "issue230",
            "path": "arki_query_output.arkimet",
            "type": "file",
})
summary = ds.query_summary()
print(summary.to_python())
EOF

$ docker run -v/tmp:/data -w/data arpaesimc/centos:7 /bin/bash -c "yum list -q arkimet && python3 test.py"
Installed Packages
arkimet.x86_64        1.27-1         @copr:copr.fedorainfracloud.org:simc:stable
{'items': [{'origin': {'style': 'GRIB1', 'centre': 80, 'subcentre': 255, 'process': 22}, 'product': {'style': 'GRIB1', 'origin': 80, 'table': 2, 'product': 1}, 'level': {'style': 'GRIB1', 'level_type': 1}, 'timerange': {'style': 'GRIB1', 'trange_type': 0, 'unit': 1, 'p1': 0, 'p2': 0}, 'area': {'style': 'GRIB', 'value': {'Ni': 1083, 'Nj': 559, 'latfirst': -13050000, 'latlast': 12060000, 'latp': -47000000, 'lonfirst': -25290000, 'lonlast': 23400000, 'lonp': 10000000, 'rot': 0, 'type': 10}}, 'proddef': {'style': 'GRIB', 'value': {'tod': 1}}, 'run': {'style': 'MINUTE', 'value': 0}, 'summarystats': {'b': datetime.datetime(2019, 6, 24, 0, 0), 'e': datetime.datetime(2019, 6, 24, 0, 0), 'c': 1, 's': 1210914}}, {'origin': {'style': 'GRIB1', 'centre': 80, 'subcentre': 255, 'process': 22}, 'product': {'style': 'GRIB1', 'origin': 80, 'table': 2, 'product': 1}, 'level': {'style': 'GRIB1', 'level_type': 1}, 'timerange': {'style': 'GRIB1', 'trange_type': 0, 'unit': 1, 'p1': 1, 'p2': 0}, 'area': {'style': 'GRIB', 'value': {'Ni': 1083, 'Nj': 559, 'latfirst': -13050000, 'latlast': 12060000, 'latp': -47000000, 'lonfirst': -25290000, 'lonlast': 23400000, 'lonp': 10000000, 'rot': 0, 'type': 10}}, 'proddef': {'style': 'GRIB', 'value': {'tod': 1}}, 'run': {'style': 'MINUTE', 'value': 0}, 'summarystats': {'b': datetime.datetime(2019, 6, 21, 0, 0), 'e': datetime.datetime(2019, 6, 21, 0, 0), 'c': 1, 's': 1210914}}]}

$ docker run -v/tmp:/data -w/data arpaesimc/centos:8 /bin/bash -c "dnf list -q arkimet && python3 test.py"
Installed Packages
arkimet.x86_64        1.27-1         @copr:copr.fedorainfracloud.org:simc:stable
Available Packages
arkimet.src           1.27-1         copr:copr.fedorainfracloud.org:simc:stable 
{'items': [{'origin': {'style': 'GRIB1', 'centre': 80, 'subcentre': 255, 'process': 22}, 'product': {'style': 'GRIB1', 'origin': 80, 'table': 2, 'product': 1}, 'level': {'style': 'GRIB1', 'level_type': 1}, 'timerange': {'style': 'GRIB1', 'trange_type': 0, 'unit': 1, 'p1': 1, 'p2': 0}, 'area': {'style': 'GRIB', 'value': {'Ni': 1083, 'Nj': 559, 'latfirst': -13050000, 'latlast': 12060000, 'latp': -47000000, 'lonfirst': -25290000, 'lonlast': 23400000, 'lonp': 10000000, 'rot': 0, 'type': 10}}, 'proddef': {'style': 'GRIB', 'value': {'tod': 1}}, 'run': {'style': 'MINUTE', 'value': 0}, 'summarystats': {'b': datetime.datetime(2019, 6, 21, 0, 0), 'e': datetime.datetime(2019, 6, 21, 0, 0), 'c': 1, 's': 1210914}}, {'origin': {'style': 'GRIB1', 'centre': 80, 'subcentre': 255, 'process': 22}, 'product': {'style': 'GRIB1', 'origin': 80, 'table': 2, 'product': 1}, 'level': {'style': 'GRIB1', 'level_type': 1}, 'timerange': {'style': 'GRIB1', 'trange_type': 0, 'unit': 1, 'p1': 0, 'p2': 0}, 'area': {'style': 'GRIB', 'value': {'Ni': 1083, 'Nj': 559, 'latfirst': -13050000, 'latlast': 12060000, 'latp': -47000000, 'lonfirst': -25290000, 'lonlast': 23400000, 'lonp': 10000000, 'rot': 0, 'type': 10}}, 'proddef': {'style': 'GRIB', 'value': {'tod': 1}}, 'run': {'style': 'MINUTE', 'value': 0}, 'summarystats': {'b': datetime.datetime(2019, 6, 24, 0, 0), 'e': datetime.datetime(2019, 6, 24, 0, 0), 'c': 1, 's': 1210914}}]}

```

**Comment by spanezz** [comment] 2020-07-07 11:14
I implemented reading/writing summary and metadata to/from json, with optional annotations.

I also documented how to use a formatter. See "Formatting the contents of metadata" among the Python HOWTOs.

The issue of the segfault remains, although at the moment I have no way to reproduce it or debug it. I'm not sure whether to leave this issue open, or to open a new issue specifically for the segfault

**Comment by bchiavarini** [comment] 2020-07-07 13:17
ok, thank you very much!
i'm sorry i can't be more useful to help reproducing the segfault issue..i will try the code through a script to see if the problem is risen by the python console. Although this is no a blocking issue as i have already found a workaround using the json summary exporter

**Comment by bchiavarini** [comment] 2020-07-07 14:06
these new commits have been included in your docker image?

**Comment by edigiacomo** [comment] 2020-07-08 07:01
Ok, then I close this issue (feel free to open a new one when you can reproduce the segfault).

> these new commits have been included in your docker image?

I'll write you an email as soon as I've released it.

**Closed by edigiacomo** 2020-07-08 07:01 UTC
