### ISSUE TITLE
CentOS7 build failing netcdf tests

### ISSUE THREAD

**Issue by brancomat** [ARPA-SIMC/arkimet#243] opened 2020-11-25 07:23 UTC
full log: https://travis-ci.org/github/ARPA-SIMC/arkimet/jobs/745605631#L3272

relevant bit:
```
======================================================================
ERROR: Scan a NetCDF 5 file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/rpmbuild/BUILD/arkimet-master/python/tests/test_scan_nc.py", line 86, in test_nc5
    md = self.read("inbound/netcdf/empty1-5.nc", 1988)
  File "/root/rpmbuild/BUILD/arkimet-master/python/tests/test_scan_nc.py", line 18, in read
    mds = ds.query_data()
  File "/root/rpmbuild/BUILD/arkimet-master/python/arkimet/scan/nc.py", line 16, in scan
    with netCDF4.Dataset(pathname, "r") as f:
  File "netCDF4/_netCDF4.pyx", line 1848, in netCDF4._netCDF4.Dataset.__init__
OSError: NetCDF: Unknown file format

----------------------------------------------------------------------
```

Should the fix turn out to be onerous: unless @dcesari has objections, it could be acceptable to remove new features from CentOS7 (autodetecting things in `configure.ac` or by flag to be activated in the spec file), but I'd rather have CentOS7 builds still compiling in case we need a fix on production server (the HPC cluster still runs that OS)

**Comment by spanezz** [comment] 2020-11-27 16:34
I suppose in this case the NetCDF library in Centos7 cannot open NetCDF version 5. I generated test cases with all possible output formats of the `ncgen` utility in my system in order to be compehensive, but if we don't need to handle files of that format, I can just remove that one from the test cases.

**Comment by brancomat** [comment] 2020-11-30 08:28
Would it be possible to test for NetCDF library version and turn off the NetCDF 5 scan test for older versions?
Right now I ignore what version started supporting it, but I can look into it if it's doable.

Another possibility would be to pass some option/flag from the spec file to the `configure` or `make test` command to manually disable that test only for CentOS7

**Comment by dcesari** [comment] 2020-11-30 08:35
I would favor to consider "unsupported format" error not to be a failure, if we can distinguish, or temporarily disable tests on version 5 file format, since we don't have the compelling need to support it on every system in short time.

**Comment by dcesari** [comment] 2020-11-30 08:37
OTOH I would not lose time trying to support version 5 on CentOS7.

**Comment by spanezz** [comment] 2020-11-30 14:31
I've commented out the NetCDF 5 tests, invoking [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). We can always uncomment them if we'll need them, and in that case we'll know what they are for, and in which platforms we'll need them.

I'm not closing the bug until I'll see if the rest of the NetCDF tests work fine on Centos7

**Comment by spanezz** [comment] 2020-12-06 18:58
Tests are green on Centos7, Centos8, and Fedora 32.

Fedora 31 seems to have problems setting up the CI build.

Fedora 33 has a segfault that I cannot reproduce on the other distributions. I'd need a Fedora 33 machine to try it out.

**Closed** 2021-05-20 06:17 UTC
Labels: bug
