### ISSUE TITLE
VM2 repack: warning messages about wrong order and overlapping items

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/arkimet#237] opened 2020-10-14 06:19 UTC
It seems that arki-check can't resolve some problems about wrong order and overlapping items (see attached dataset 
[rmap.zip](https://github.com/ARPA-SIMC/arkimet/files/5376018/rmap.zip)).
 
```
[arkimet@arkioss8 ~]$ arki-query --version
1.29
[arkimet@arkioss8 ~]$ arki-check --filter "reftime:=2020-07-31" /arkivio/arkimet/dataset/rmap
rmap:2020/07-31.vm2: item at offset 1616 is wrongly ordered before item at offset 156187
rmap:2020/07-31.vm2: item at offset 155196 overlaps with the previous items that ends at offset 155198
rmap: check 0 files ok
[arkimet@arkioss8 ~]$ arki-check --filter "reftime:=2020-07-31" -f /arkivio/arkimet/dataset/rmap
rmap:2020/07-31.vm2: item at offset 1616 is wrongly ordered before item at offset 156187
rmap:2020/07-31.vm2: item at offset 155196 overlaps with the previous items that ends at offset 155198
rmap: check 0 files ok
[arkimet@arkioss8 ~]$ arki-check --filter "reftime:=2020-07-31" -f -r /arkivio/arkimet/dataset/rmap
rmap:2020/07-31.vm2: item at offset 1616 is wrongly ordered before item at offset 156187
rmap:2020/07-31.vm2: item at offset 155196 overlaps with the previous items that ends at offset 155198
rmap: repack 0 files ok
[arkimet@arkioss8 ~]$ arki-check --filter "reftime:=2020-07-31" /arkivio/arkimet/dataset/rmap
rmap:2020/07-31.vm2: item at offset 1616 is wrongly ordered before item at offset 156187
rmap:2020/07-31.vm2: item at offset 155196 overlaps with the previous items that ends at offset 155198
rmap: check 0 files ok
```

**Comment by edigiacomo** [comment] 2020-10-14 06:20
Update: is it something related to #187?

**Comment by spanezz** [comment] 2020-10-14 13:19
It does not seem related. In this case, if I run: `arki-query 'reftime:=2020-07-31' issue237/ --yaml`, I get something like this in the output:
```
…
Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/issue237/2020/07-31.vm2:1526+44)
Note: [2020-09-15T06:25:47Z]Scanned from 07-31.vm2

Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/issue237/2020/07-31.vm2:1571+44)
Note: [2020-09-15T06:25:47Z]Scanned from 07-31.vm2

Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/issue237/2020/07-31.vm2:155196+46)
Note: [2020-09-16T12:57:22Z]Scanned from calcola_dati_climat_202030_20200916123548136658869_aa.vm2

Source: BLOB(vm2,/home/enrico/lavori/arpa/arkimet/issue237/2020/07-31.vm2:155151+46)
Note: [2020-09-16T12:57:22Z]Scanned from calcola_dati_climat_202030_20200916123548136658869_aa.vm2
…
```

Looking at offset+size in the first 2, they are consistent: 1626+44=1570, plus the newline and the next start at 1571.

However, 155151+46=155197, but the other data starts at 155196. The data file itself does not seem corrupted, so it looks like the size itself is wrong. Indeed the line at 155151 is 44 characters, not 46.

I see two issues:
* the size is computed wrong: why?
* in `arki/dataset/maintenance.cc`, the case of `SEGMENT_CORRUPTED` is not handled. That is correct, as it doesn't know what to do in that case and it makes sense to leave it to manual intervention. However, it misses actually letting you know(!) that it needs manual intervention and it won't attempt a fix

Since the data does not seem corrupted, manual intervention in this case could be to rescan the file. It would be very good to understand why the size was wrong. Could it be that some data was scanned that had MSDOS newlines (I'm suspicious at the2 extra bytes), and something got confused?

**Comment by spanezz** [comment] 2020-10-14 14:12
Meanwhile I pushed a fix for the reporting issue

**Comment by edigiacomo** [comment] 2020-10-15 08:56
Thanks Enrico!

Those records are created with a Python `print` function on a CentOS server, then I think it's not possible that those files have a MSDOS newline.

I don't know if it's useful, but it seems that the offset too is miscalculated (whereas the size sometimes is right):

```
[edg@oliva Downloads]$ tail -c +1526 rmap/2020/07-31.vm2| head -c 44

202007310000,53069,158,27.109990,,,00000000[edg@oliva Downloads]
```

```
[edg@oliva Downloads]$ tail -c +155151 rmap/2020/07-31.vm2| head -c 46

202007310000,53066,231,28.889990,,,000000000
[edg@oliva Downloads]$
```

**Comment by edigiacomo** [comment] 2020-10-21 15:00
Sorry, my fault, the offset is ok.

**Comment by spanezz** [comment] 2020-11-03 09:19
Ok. `SEGMENT_CORRUPTED` is now handled, and I'm not sure how to debug why the size was reported wrong.

Has the problem appeared again?

**Comment by edigiacomo** [comment] 2020-11-03 09:29
Yes, with a recent segment (e.g. 2 days ago), but using the same arkimet version (1.29). I could create a new release, rescan the file and then wait for the same problem to happen.

**Comment by edigiacomo** [comment] 2020-11-03 09:35
Better late than never, it occurred to me that I can reproduce the sequence of data imported in a dataset, because I keep the imported files of the last 30 days. I'll try to reproduce the problem.

**Comment by edigiacomo** [comment] 2020-11-03 10:05
You can reproduce the issue (see [issue_237.zip](https://github.com/ARPA-SIMC/arkimet/files/5480466/issue_237.zip))

```
$ arki-query --version
1.29

$ bash runtest.sh
+ arki-check -f --remove-all dataset/error dataset/profe
profe:2020/10-31.vm2: deleted (145086 freed)                                                                           
profe:2020/11-01.vm2: deleted (177939 freed)                                                                           
+ arki-mergeconf dataset/error dataset/profe                                                                           
+ arki-scan --dispatch=conf --dump --summary --status rmap_meteonetwork_20201101002401901753264.VM2 rmap_meteonetwork_20201101012402714515623.VM2
WARNING rmap_meteonetwork_20201101012402714515623.VM2: everything ok: 269 messages imported in 0.057502 seconds        
WARNING rmap_meteonetwork_20201101002401901753264.VM2: everything ok: 177 messages imported in 0.018859 seconds
....
....
+ arki-check dataset/error dataset/profe
profe:2020/10-31.vm2: item at offset 2911 begins past the end of the previous item (offset 0)
profe:2020/10-31.vm2: item at offset 2946 overlaps with the previous items that ends at offset 2948
profe:2020/11-01.vm2: item at offset 3368 is wrongly ordered before item at offset 9967
profe:2020/11-01.vm2: item at offset 3403 overlaps with the previous items that ends at offset 3405
profe: check 0 files ok
error: check 0 files ok
+ arki-check -f dataset/error dataset/profe
profe:2020/10-31.vm2: item at offset 2911 begins past the end of the previous item (offset 0)
profe:2020/10-31.vm2: item at offset 2946 overlaps with the previous items that ends at offset 2948
profe:2020/11-01.vm2: item at offset 3368 is wrongly ordered before item at offset 9967
profe:2020/11-01.vm2: item at offset 3403 overlaps with the previous items that ends at offset 3405
profe: check 0 files ok
error: check 0 files ok
+ arki-check -fr dataset/error dataset/profe
profe:2020/10-31.vm2: item at offset 2911 begins past the end of the previous item (offset 0)
profe:2020/10-31.vm2: item at offset 2946 overlaps with the previous items that ends at offset 2948
profe:2020/11-01.vm2: item at offset 3368 is wrongly ordered before item at offset 9967
profe:2020/11-01.vm2: item at offset 3403 overlaps with the previous items that ends at offset 3405
profe: repack 0 files ok
error: repack: running VACUUM ANALYZE on the dataset index, if applicable
error: repack 0 files ok
+ arki-check dataset/error dataset/profe
profe:2020/10-31.vm2: item at offset 2911 begins past the end of the previous item (offset 0)
profe:2020/10-31.vm2: item at offset 2946 overlaps with the previous items that ends at offset 2948
profe:2020/11-01.vm2: item at offset 3368 is wrongly ordered before item at offset 9967
profe:2020/11-01.vm2: item at offset 3403 overlaps with the previous items that ends at offset 3405
profe: check 0 files ok
error: check 0 files ok
```

**Comment by spanezz** [comment] 2020-11-03 12:13
Ok, reproduced.

The core of the issue is that we have VM2 entries like `20201031230000,12865,158,9.409990,,,` that after a reconstruct become `202010312300,12865,158,9.409990,,,` (i.e. the seconds, being zero, are truncated).

This breaks the invariant that the data that comes off a `get_data` has the same size as the size declared in the `source` metadata. In fact, with a VM2 using smallfiles, data might enter a dataset with `00` seconds, and come out without (after smallfiles reconstruction). This breaks a bit the expectation that arkimet doesn't change the binary data as it goes through datasets.

For VM2 this is less of a problem. There can be ways to deal with this:

 - on VM2 scan, do not use reconstruct and always keep the original data
 - when writing to a dataset, always reconstruct and adjust source size before writing
 - amend the VM2 format to remove the seconds, which are unused at the moment, removing the ambiguity

It might also make sense, when smallfiles is used, to make it so that on arki-check, arkimet also verifies that the reconstructed value parses the same as the original.

If instead we decide to buy into "for some specific formats what comes out might not be the same as went in", we can normalise the VM2 on dataset ingestion, minimizing them by, for example, removing seconds or even minutes and hours in case they're zeroes, and stripping trailing commas if any.

Comments?

**Comment by edigiacomo** [comment] 2020-11-03 12:48
> amend the VM2 format to remove the seconds, which are unused at the moment, removing the ambiguity

I don't see any problem removing the seconds from VM2 format. I just have to adapt some programs.

Otherwise (or in addition to the removal of the seconds in VM2 format), we could store the original data in smallfiles (in VM2, it's only an increase of 12-14 bytes per record, that is a total increase of ~15GB): this could restore too the expectation that arkimet doesn't change the data both in the archive and in the response of the arki-query.

**Comment by spanezz** [comment] 2020-11-05 17:54
I've implemented a normalisation function, used only at `arki-scan --dispatch` time, in `arki/scan/vm2.cc:265`.

It might be that reparsing orig and using meteo-vm2 to make a condensed version might be more performant, but one can't say without measurements.

Now possible ambiguities in VM2 representation are resolved at acquisition time.

**Closed** 2020-11-05 17:53 UTC
