### ISSUE TITLE
ERROR formatter failed

### ISSUE THREAD

**Issue by lidiabressan** [ARPA-SIMC/arkimet#321] opened 2023-12-01 11:23 UTC
ciao !

i got an error in this file (grib2) for level (here the 1st message):
[pres.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/13525890/pres.tar.gz) 

arki-scan --dump --annotate  grib:pres.grb

ERROR formatter failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/arkimet/formatter/formatter.py", line 39, in format
    res = formatter(t)
  File "/usr/lib/python3.6/site-packages/arkimet/formatter/level.py", line 48, in format_level
    return format_single_level(type1, scale1, value1) + " " + format_single_level(type2, scale2, value2)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

[pres.tar.gz](https://github.com/ARPA-SIMC/arkimet/files/13525890/pres.tar.gz)

**Comment by dcesari** [comment] 2023-12-01 11:57
It is probably a duplicate of #317, can we close that issue merging in a new release?

**Comment by brancomat** [comment] 2023-12-04 16:07
arkimet v1.48-1 has been installed on internal server "rocky8"
please test if this version gives the same error

**Comment by dcesari** [comment] 2023-12-06 10:35
Actually it seems an unimplemented feature:
https://github.com/ARPA-SIMC/arkimet/blob/75b0fc58d0714ec141c3655f8ab8fd764028e718/python/arkimet/formatter/level.py#L22

**Comment by spanezz** [comment] 2023-12-06 16:39
A possible quick fix could be to change `default_table_version` in https://github.com/ARPA-SIMC/arkimet/blob/75b0fc58d0714ec141c3655f8ab8fd764028e718/python/arkimet/formatter/eccodes.py#L112 to something newer (15?)

A proper fix requires to add a way to give `format_level` access to `centre, table_version, local_table_version`, which are currently not stored in the level metadata.

The problem is that those values might not always be available when trying to format a level: for example, trying to format a summary that contains only Level information, without origin and the like.

However, for a proper fix the problem is wider: if the level *does* require those other information to be interpreted, it may be insufficiently defined. Would a level with a given value with table version 4 mean something else with table version 15? If so, we might have to add the table version to the level information, like we have with products.

If however it's just a case of levels being added without being redefined, the quick fix of updating `default_table_version` might end up being the proper fix for just adding support for the new levels

**Comment by dcesari** [comment] 2024-04-30 10:25
I propose a pull request. As far as I know, the new table versions add or deprecate entries, but they should not change the content of existing entries except for cosmetic corrections.

**Comment by brancomat** [comment] 2024-05-10 12:57
The pull request has been merged in arkimet v1.50-1 (already available in copr repos)

**Closed** 2024-07-17 07:43 UTC
Labels: review
